[package]
name = "rust_bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
glam = "0.33.5"
# Point this to the local submodule path
rocketsim = { path = "../submodules/RocketSim/rocketsim" }
rocketsim_vis = { path = "../submodules/RocketSim/rocketsim_vis" }

[target.'cfg(not(any(target_arch = "x86", target_arch = "x86_64")))'.dependencies]
# use glam with experimental support for portable SIMD when not running on x86
# architectures
glam = { version = "0.33.5", features = ["core-simd"], optional = true }
